import { sql, type Kysely } from 'kysely';

/**
 * M1: users and roles, org + academic structure, sign-in state, audit log.
 * IDs are UUIDv7 generated by the app (ADR-0011).
 */
export async function up(db: Kysely<unknown>): Promise<void> {
  await sql`
    create function argus_touch_updated_at() returns trigger language plpgsql as $$
    begin new.updated_at := now(); return new; end $$;

    -- ─── Identity ────────────────────────────────────────────────────────────
    create table users (
      id uuid primary key,
      role text not null check (role in ('student','teacher','acadops','verifier','admin')),
      name text not null check (length(trim(name)) > 0),
      email text not null,
      sso_subject text unique,
      status text not null default 'active' check (status in ('active','disabled')),
      created_at timestamptz not null default now(),
      updated_at timestamptz not null default now()
    );
    create unique index users_email_lower_uq on users (lower(email));

    create table departments (
      id uuid primary key,
      code text not null unique,
      name text not null,
      created_at timestamptz not null default now(),
      updated_at timestamptz not null default now()
    );

    create table programs (
      id uuid primary key,
      code text not null unique,
      name text not null,
      department_id uuid not null references departments(id),
      created_at timestamptz not null default now(),
      updated_at timestamptz not null default now()
    );

    create table terms (
      id uuid primary key,
      name text not null unique,
      start_date date not null,
      end_date date not null,
      created_at timestamptz not null default now(),
      updated_at timestamptz not null default now(),
      check (end_date > start_date)
    );

    create table sections (
      id uuid primary key,
      program_id uuid not null references programs(id),
      term_id uuid not null references terms(id),
      name text not null,
      created_at timestamptz not null default now(),
      updated_at timestamptz not null default now(),
      unique (term_id, program_id, name)
    );

    -- Lab batches within a section (spec: section_groups).
    create table section_groups (
      id uuid primary key,
      section_id uuid not null references sections(id) on delete cascade,
      name text not null,
      created_at timestamptz not null default now(),
      updated_at timestamptz not null default now(),
      unique (section_id, name),
      unique (id, section_id)
    );

    create table students (
      user_id uuid primary key references users(id) on delete cascade,
      usn text not null unique,
      program_id uuid not null references programs(id),
      section_id uuid references sections(id),
      -- Default lab batch within the section; used when enrollments are generated.
      group_id uuid,
      admission_year int not null check (admission_year between 1990 and 2100),
      created_at timestamptz not null default now(),
      updated_at timestamptz not null default now(),
      foreign key (group_id, section_id) references section_groups (id, section_id)
    );

    create table teachers (
      user_id uuid primary key references users(id) on delete cascade,
      faculty_id text not null unique,
      department_id uuid not null references departments(id),
      created_at timestamptz not null default now(),
      updated_at timestamptz not null default now()
    );

    create table subjects (
      id uuid primary key,
      code text not null unique,
      name text not null,
      kind text not null check (kind in ('lecture','lab','tutorial')),
      created_at timestamptz not null default now(),
      updated_at timestamptz not null default now()
    );

    create table campus_geofences (
      id uuid primary key,
      name text not null unique,
      center_lat double precision not null check (center_lat between -90 and 90),
      center_lon double precision not null check (center_lon between -180 and 180),
      radius_m double precision not null check (radius_m > 0 and radius_m <= 20000),
      polygon jsonb,
      created_at timestamptz not null default now(),
      updated_at timestamptz not null default now()
    );

    create table rooms (
      id uuid primary key,
      code text not null unique,
      building text not null default '',
      floor int,
      capacity int check (capacity is null or capacity > 0),
      geofence_id uuid references campus_geofences(id),
      ble_rssi_threshold int, -- Phase 2 hook
      created_at timestamptz not null default now(),
      updated_at timestamptz not null default now()
    );

    create table campus_networks (
      id uuid primary key,
      cidr cidr not null unique,
      label text not null default '',
      created_at timestamptz not null default now(),
      updated_at timestamptz not null default now()
    );

    -- ─── Academic ────────────────────────────────────────────────────────────
    create table course_offerings (
      id uuid primary key,
      term_id uuid not null references terms(id),
      subject_id uuid not null references subjects(id),
      section_id uuid not null references sections(id),
      created_at timestamptz not null default now(),
      updated_at timestamptz not null default now(),
      unique (term_id, subject_id, section_id)
    );

    create table enrollments (
      id uuid primary key,
      student_id uuid not null references students(user_id) on delete cascade,
      offering_id uuid not null references course_offerings(id) on delete cascade,
      group_id uuid references section_groups(id),
      created_at timestamptz not null default now(),
      updated_at timestamptz not null default now(),
      unique (student_id, offering_id)
    );

    create table teaching_assignments (
      id uuid primary key,
      teacher_id uuid not null references teachers(user_id) on delete cascade,
      offering_id uuid not null references course_offerings(id) on delete cascade,
      group_id uuid references section_groups(id),
      role text not null default 'primary' check (role in ('primary','assistant')),
      created_at timestamptz not null default now(),
      updated_at timestamptz not null default now()
    );
    create unique index teaching_assignments_uq
      on teaching_assignments (teacher_id, offering_id, coalesce(group_id, '00000000-0000-0000-0000-000000000000'::uuid));

    -- ─── Sign-in state ───────────────────────────────────────────────────────
    create table web_sessions (
      id_hash text primary key,              -- SHA-256 of the cookie value; the value itself is never stored
      user_id uuid not null references users(id) on delete cascade,
      csrf_token text not null,
      auth_at timestamptz not null,          -- last time the user authenticated at the IdP (re-auth checks)
      created_at timestamptz not null default now(),
      expires_at timestamptz not null,
      last_seen_at timestamptz not null default now(),
      revoked_at timestamptz,
      ip inet,
      user_agent text
    );
    create index web_sessions_user_idx on web_sessions (user_id);

    create table oidc_login_states (
      state text primary key,
      nonce text not null,
      code_verifier text not null,
      client text not null check (client in ('web','mobile')),
      next_path text,
      app_code_challenge text,               -- mobile: S256 challenge from the app
      reauth boolean not null default false,
      expires_at timestamptz not null
    );

    create table mobile_auth_codes (
      code_hash text primary key,
      user_id uuid not null references users(id) on delete cascade,
      app_code_challenge text not null,
      expires_at timestamptz not null,
      used_at timestamptz
    );

    create table refresh_tokens (
      id uuid primary key,
      family_id uuid not null,
      user_id uuid not null references users(id) on delete cascade,
      token_hash text not null unique,
      session_key_spki text not null,        -- device session key (ADR-0008); refresh requests must be signed with it
      created_at timestamptz not null default now(),
      expires_at timestamptz not null,
      used_at timestamptz,                   -- rotated; reuse of a used token revokes the family
      revoked_at timestamptz
    );
    create index refresh_tokens_family_idx on refresh_tokens (family_id);

    create table policy_acceptances (
      user_id uuid not null references users(id) on delete cascade,
      policy_version text not null,
      accepted_at timestamptz not null default now(),
      primary key (user_id, policy_version)
    );

    -- ─── Audit (append-only, hash-chained; ADR-0013) ─────────────────────────
    create table audit_log (
      id bigserial primary key,
      actor_id uuid,
      action text not null,
      entity_type text not null,
      entity_id text,
      before jsonb,
      after jsonb,
      ip text,
      at timestamptz not null,
      prev_hash text not null,
      hash text not null unique
    );
    create index audit_log_entity_idx on audit_log (entity_type, entity_id);
    create index audit_log_actor_idx on audit_log (actor_id);

    create function argus_audit_immutable() returns trigger language plpgsql as $$
    begin raise exception 'audit_log is append-only'; end $$;
    create trigger audit_log_no_update before update or delete on audit_log
      for each row execute function argus_audit_immutable();
    create trigger audit_log_no_truncate before truncate on audit_log
      for each statement execute function argus_audit_immutable();

    create table audit_checkpoints (
      id bigserial primary key,
      last_audit_id bigint not null,
      last_hash text not null,
      created_at timestamptz not null default now()
    );
  `.execute(db);

  for (const t of [
    'users', 'departments', 'programs', 'terms', 'sections', 'section_groups', 'students', 'teachers',
    'subjects', 'campus_geofences', 'rooms', 'campus_networks', 'course_offerings', 'enrollments',
    'teaching_assignments',
  ]) {
    await sql`create trigger ${sql.raw(`${t}_touch`)} before update on ${sql.table(t)}
      for each row execute function argus_touch_updated_at()`.execute(db);
  }
}

export async function down(): Promise<void> {
  throw new Error('0002 is not reversible; restore from backup instead');
}
